import React from 'react';

export const GeminiBadge: React.FC<{ agentName?: string }> = ({ agentName }) => (
  <span
    className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-blue-50 border border-blue-100 text-[10px] font-semibold text-blue-700"
    aria-label={`Generated by Google Gemini AI${agentName ? ` — ${agentName} Agent` : ''}`}
  >
    <span aria-hidden="true">✦</span>
    Powered by Gemini
    {agentName && <span className="text-blue-500 font-normal">· {agentName}</span>}
  </span>
);
